### ISSUE TITLE
Support primary and fallback both being ovos-stt-http-server instances

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-stt-http-server#5]
Currently, this option works great for either a primary STT server or a fallback STT server. However, if I want to use it for primary **and** fallback, I cannot. There is no way to differentiate them in the config.

Ideally we could use ovos-stt-http-server for both STT configurations and keep everything local and private.

**Comment by mikejgray** [comment]
@JarbasAl This is supported now, isn't it?

**Comment by JarbasAl** [comment]
now a list of servers is supported as part of plugin config, no need for 2 plugins, just try servers by order until one works effectively giving unlimited number of fallbacks

closing
