### ISSUE TITLE
README.md the Dockerfile ENTRYPOINT command is incorrect

### ISSUE THREAD

**Issue by ShuffleBit** [OpenVoiceOS/ovos-stt-http-server#8]
When installed via pip, ovos-stt-http-server is executable as "ovos-stt-server" so the Dockerfile example's ENTRYPOINT should be "ovos-stt-server" and not "ovos-stt-http-server".

As-is, it causes a "/bin/sh: 1: ovos-stt-http-server not found" error when the image is run.

**Comment by goldyfruit** [comment]
@ShuffleBit I'm building Docker images as well for STT, please have a look here https://github.com/OpenVoiceOS/ovos-docker-stt _(for early birds)_.

**Comment by NeonDaniel** [comment]
Closed by #6
